# Generated by Django 4.2.6 on 2023-10-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieorder_movie_movie_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieorder',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movieorder',
            name='user',
        ),
    ]
