# Generated by Django 4.2.6 on 2023-10-14 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_remove_movieorder_movie_remove_movieorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_order',
            field=models.ManyToManyField(related_name='movie_order', through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MovieOrder',
        ),
    ]
